disabled_rules:
  - force_cast
  - identifier_name
  - leading_whitespace
  - todo
  - trailing_whitespace
  - void_return
  - cyclomatic_complexity
  - implicit_getter
  - trailing_newline
  - syntactic_sugar
  - literal_expression_end_indentation
  - unneeded_parentheses_in_closure_argument
  - colon
  - implicitly_unwrapped_optional
  - nesting
  - unused_closure_parameter
  - discarded_notification_center_observer
  - operator_whitespace
  - function_body_length
excluded:
  - Submodules/
  - RxAlamofire/
  - Pods/
  - vendor/bundle
opt_in_rules:
  - empty_string
  - fatal_error_message
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - override_in_extension
  - required_enum_case
  - yoda_condition
file_length:
  warning: 800
  error: 2000
line_length:
  warning: 150
  error: 160
type_body_length:
  warning: 500
  error: 1000
