disabled_rules:
  - force_cast
  - identifier_name
  - leading_whitespace
  - todo
  - trailing_whitespace
  - void_return
excluded:
  - Submodules/
  - RxAlamofire/
  - Pods/
  - vendor/bundle
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - discouraged_optional_boolean
  - empty_string
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - override_in_extension
  - private_action
  - private_outlet
  - required_enum_case
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
file_length:
  warning: 800
  error: 1200
function_body_length:
  warning: 40
  error: 50
line_length:
  warning: 150
  error: 160
type_body_length:
  warning: 500
  error: 1000
